# This script is released as a part of Monteys et al., Nature (2021)
# This script was used to identify splice events unique to the LMI070 treated condition.
# It takes as input SJ.out.tab format splice junction files generated by the STAR RNA-Seq aligner.

library(readr)
ctrl_9_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/ctrl_9_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE,
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)
ctrl_10_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/ctrl_10_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE, 
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)
ctrl_11_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/ctrl_11_SJ.out.tab", 
                             "\t", escape_double = FALSE, col_names = FALSE, 
                             col_types = cols(X1 = col_character(), 
                                              X2 = col_integer(), X3 = col_integer(), 
                                              X4 = col_integer(), X5 = col_integer(), 
                                              X6 = col_integer(), X7 = col_integer(), 
                                              X8 = col_integer(), X9 = col_integer()), 
                             trim_ws = TRUE)
ctrl_12_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/ctrl_12_SJ.out.tab", 
                             "\t", escape_double = FALSE, col_names = FALSE, 
                             col_types = cols(X1 = col_character(), 
                                              X2 = col_integer(), X3 = col_integer(), 
                                              X4 = col_integer(), X5 = col_integer(), 
                                              X6 = col_integer(), X7 = col_integer(), 
                                              X8 = col_integer(), X9 = col_integer()), 
                             trim_ws = TRUE)
trd_13_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/trd_13_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE, 
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)
trd_14_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/trd_14_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE, 
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)
trd_15_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/trd_15_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE, 
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)
trd_16_SJ_out <- read_delim("~/Documents/Davidson_Lab/Alex/Alex_Splicing/trd_16_SJ.out.tab", 
                            "\t", escape_double = FALSE, col_names = FALSE, 
                            col_types = cols(X1 = col_character(), 
                                             X2 = col_integer(), X3 = col_integer(), 
                                             X4 = col_integer(), X5 = col_integer(), 
                                             X6 = col_integer(), X7 = col_integer(), 
                                             X8 = col_integer(), X9 = col_integer()), 
                            trim_ws = TRUE)

colnames(ctrl_9_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(ctrl_10_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(ctrl_11_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(ctrl_12_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(trd_13_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(trd_14_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(trd_15_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")
colnames(trd_16_SJ_out) <- c("Chr","fbINT","lbINT","Strand","Unknown","Annotation","UniquelyMapped","MultiMapped","Unknown")

ctrl_9_SJ_out["POS"] <- paste(ctrl_9_SJ_out$Chr,":",ctrl_9_SJ_out$fbINT,"-",ctrl_9_SJ_out$lbINT, sep = "")
ctrl_10_SJ_out["POS"] <- paste(ctrl_10_SJ_out$Chr,":",ctrl_10_SJ_out$fbINT,"-",ctrl_10_SJ_out$lbINT, sep = "")
ctrl_11_SJ_out["POS"] <- paste(ctrl_11_SJ_out$Chr,":",ctrl_11_SJ_out$fbINT,"-",ctrl_11_SJ_out$lbINT, sep = "")
ctrl_12_SJ_out["POS"] <- paste(ctrl_12_SJ_out$Chr,":",ctrl_12_SJ_out$fbINT,"-",ctrl_12_SJ_out$lbINT, sep = "")
trd_13_SJ_out["POS"] <- paste(trd_13_SJ_out$Chr,":",trd_13_SJ_out$fbINT,"-",trd_13_SJ_out$lbINT, sep = "")
trd_14_SJ_out["POS"] <- paste(trd_14_SJ_out$Chr,":",trd_14_SJ_out$fbINT,"-",trd_14_SJ_out$lbINT, sep = "")
trd_15_SJ_out["POS"] <- paste(trd_15_SJ_out$Chr,":",trd_15_SJ_out$fbINT,"-",trd_15_SJ_out$lbINT, sep = "")
trd_16_SJ_out["POS"] <- paste(trd_16_SJ_out$Chr,":",trd_16_SJ_out$fbINT,"-",trd_16_SJ_out$lbINT, sep = "")

CTRL_Merged_ALL <- merge(ctrl_9_SJ_out, ctrl_10_SJ_out, by = "POS", all = TRUE)
CTRL_Merged_ALL <- merge(CTRL_Merged_ALL, ctrl_11_SJ_out, by = "POS", all = TRUE)
CTRL_Merged_ALL <- merge(CTRL_Merged_ALL, ctrl_12_SJ_out, by = "POS", all = TRUE)

Trd_Merged_ALL <- merge(trd_13_SJ_out, trd_14_SJ_out, by = "POS", all = TRUE)
Trd_Merged_ALL <- merge(trd_15_SJ_out, Trd_Merged_ALL, by = "POS", all = TRUE)
Trd_Merged_ALL <- merge(trd_16_SJ_out, Trd_Merged_ALL, by = "POS", all = TRUE)


# Calculate Mean and Standard Deviation of the Uniquely Mapped reads
CTRL_Values <- data.frame(CTRL_Merged_ALL[,8],CTRL_Merged_ALL[,17],CTRL_Merged_ALL[,26],CTRL_Merged_ALL[,35])
CTRL_Values[is.na(CTRL_Values)] <- 0
CTRL_Mean <- rowMeans(CTRL_Values)
CTRL_Sd <- apply(CTRL_Values, 1, sd)

Trd_Values <- data.frame(Trd_Merged_ALL[,8],Trd_Merged_ALL[,17],Trd_Merged_ALL[,26],Trd_Merged_ALL[,35])
Trd_Values[is.na(Trd_Values)] <- 0
Trd_Mean <- rowMeans(Trd_Values)
Trd_Sd <- apply(Trd_Values, 1, sd)

CTRL_PolishedDF <- data.frame(CTRL_Merged_ALL$POS,
                              CTRL_Merged_ALL$Chr.x, 
                              CTRL_Merged_ALL$fbINT.x, 
                              CTRL_Merged_ALL$lbINT.x, 
                              CTRL_Merged_ALL$Annotation.x, 
                              CTRL_Merged_ALL[,8],
                              CTRL_Merged_ALL[,17],
                              CTRL_Merged_ALL[,26],
                              CTRL_Merged_ALL[,35],
                              CTRL_Mean,
                              CTRL_Sd)
colnames(CTRL_PolishedDF) <- c("POS","Chr","fbINT","lbINT","Annotated","UniquelyMapped1", "UniquelyMapped2", "UniquelyMapped3", "UniquelyMapped4", "UM_Mean", "UM_Sd")

Trd_PolishedDF <- data.frame(Trd_Merged_ALL$POS,
                             Trd_Merged_ALL$Chr.x, 
                             Trd_Merged_ALL$fbINT.x, 
                             Trd_Merged_ALL$lbINT.x, 
                             Trd_Merged_ALL$Annotation.x, 
                             Trd_Merged_ALL[,8],
                             Trd_Merged_ALL[,17],
                             Trd_Merged_ALL[,26],
                             Trd_Merged_ALL[,35],
                             Trd_Mean,
                             Trd_Sd)
colnames(Trd_PolishedDF) <- c("POS","Chr","fbINT","lbINT","Annotated","UniquelyMapped1", "UniquelyMapped2", "UniquelyMapped3", "UniquelyMapped4", "UM_Mean", "UM_Sd")

All_DF <- merge(CTRL_PolishedDF, Trd_PolishedDF, by = "POS", all = TRUE)

# Replace NAs in the stats columns with 0
All_DF$UniquelyMapped1.x[is.na(All_DF$UniquelyMapped1.x)] <- 0
All_DF$UniquelyMapped2.x[is.na(All_DF$UniquelyMapped2.x)] <- 0
All_DF$UniquelyMapped3.x[is.na(All_DF$UniquelyMapped3.x)] <- 0
All_DF$UniquelyMapped4.x[is.na(All_DF$UniquelyMapped4.x)] <- 0
All_DF$UM_Mean.x[is.na(All_DF$UM_Mean.x)] <- 0
All_DF$UM_Sd.x[is.na(All_DF$UM_Sd.x)] <- 0

All_DF$UniquelyMapped1.y[is.na(All_DF$UniquelyMapped1.y)] <- 0
All_DF$UniquelyMapped2.y[is.na(All_DF$UniquelyMapped2.y)] <- 0
All_DF$UniquelyMapped3.y[is.na(All_DF$UniquelyMapped3.y)] <- 0
All_DF$UniquelyMapped4.y[is.na(All_DF$UniquelyMapped4.y)] <- 0
All_DF$UM_Mean.y[is.na(All_DF$UM_Mean.y)] <- 0
All_DF$UM_Sd.y[is.na(All_DF$UM_Sd.y)] <- 0

# Create a column "Diff" to represent the difference betwen control and treated averages.
Diff <- All_DF$UM_Mean.x - All_DF$UM_Mean.y
All_DF["Diff"] <- Diff


# Subset the merged dataset based on values of interest
All_DF_Sub_T <- All_DF[All_DF$UM_Mean.x <= 1,]
All_DF_Sub_T <- All_DF_Sub_T[All_DF_Sub_T$UM_Mean.y >= 0,]
All_DF_Sub_T <- All_DF_Sub_T[order(All_DF_Sub_T$UM_Mean.y, decreasing = TRUE),]
write.csv(All_DF_Sub_T, file = "./AlexDataset_DMSOvsLMI070_LessThan1.csv")
saveRDS(All_DF_Sub_T, file = "./AlexDataset_DMSOvsLMI070_LessThan1.rds")

